### ISSUE TITLE
Finalize Landing UI

### ISSUE THREAD

**Issue by PresKhaled** [PresKhaled/atlas#2]
Landing UI need more touches, I'll give it anthor look.

**Current result:**

![Current Landing UI result](https://user-images.githubusercontent.com/58700627/79933185-911b7500-844f-11ea-828e-b0eb3b9d3ae1.png)

**Comment by Fethi-Hamdani** [comment]
how about this:
- changed the logo's shadow offset and blur radius

- i lowered the Title image a bit

- lowered the opacity of the background colors to 0.9

![Screenshot_1587556695](https://user-images.githubusercontent.com/37482884/79979274-28f18100-8499-11ea-9320-40ca39695e39.png)

**Comment by PresKhaled** [comment]
@Fethi1 Excellent! 🥇 

Shadow is good but space between app name and written logo is much higher
  - [x] Low the space a little to stick with design

If you would to continue with me in this issue, you can do more
  - [x] Add Signin button shadow (like in PSD)
  - [x] Remove Signin splash ink effect

**After these you can make a pull request**
Keep going!

**Comment by Fethi-Hamdani** [comment]
I have completed the tasks mentioned above 
and i noticed that the background image is not as wide as in the PSD file 
so i had to crop to look this way, if you are ok with it i'll add a pull request to update the image file
![Screenshot_1587575580](https://user-images.githubusercontent.com/37482884/80012981-117cbd00-84c6-11ea-9663-e8b518164b0c.png)

**Comment by PresKhaled** [comment]
Shine work ✨ 

**release-long-live branch**
