### ISSUE TITLE
Signin UI

### ISSUE THREAD

**Issue by PresKhaled** [PresKhaled/atlas#3]
### Signin UI need to be done!

**Without some parts:**
<del>Signin title at the top of window</del>
<del>Keep me logged in</del>

Join the Discord channel for this issue: [Signin Channel](https://discord.gg/46mB95)

Compete with colleagues in #4 
Let's see result better than them!

**Don't forget to check [Atlas Track project](https://github.com/PresKhaled/atlas/projects/1) instructions (Information, Pinned columns) before contribution**

**UI**

![Signin UI](https://user-images.githubusercontent.com/58700627/79995297-5d743580-84b7-11ea-9a34-30a88a7a5ad9.png)

**Comment by tecgenes** [comment]
adding utilities folder and contain constants  for imagsPath variable , kGradient , kBoxShadow , dividerColor , 

adding buildDivider method in include file 

adding signin page

![Screenshot_20200423-080648](https://user-images.githubusercontent.com/48675836/80061776-d49edd80-853a-11ea-8026-dc11f55dea76.jpg)

**Comment by PresKhaled** [comment]
> adding utilities folder and contain constants for imagsPath variable , kGradient , kBoxShadow , dividerColor ,
> 
> adding buildDivider method in include file
> 
> adding signin page
> 
> ![Screenshot_20200423-080648](https://user-images.githubusercontent.com/48675836/80061776-d49edd80-853a-11ea-8026-dc11f55dea76.jpg)

Good Job! ✨ 

but there's some notes:
  - no need for utilities folder right now, use **(/inc/include.dart)** instead
     - in order not to currently affect the project hierarchy
     - _your name for folder and file is better but we will do refactoring at some point_
  - constants names is oppose the Effective dart style guide
     - [Effective Dart Style: Don't use prefix letters](https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters)
     - use the full name instead or something relative in order to other contributers understand the meaning, i don't understand the meaning of kGradient or kBoxShadow! how to know where you used these?
  - there was some instructions in the issue
    - `Without some parts:`
      - <del>Signin title at the top of window</del>
      - <del>Keep me logged in</del>
  - replace close icon with back arrow
  - add Signin button

After that make a **pull request** for changes
You did amazing work and all that alone 💯 , keep going 👍
