### ISSUE TITLE
Signup UI

### ISSUE THREAD

**Issue by PresKhaled** [PresKhaled/atlas#4]
### Signin UI need to be done!

**Without some parts:**
<del>Signup title at the top of the window</del>
<del>Close icon at the top left of the window</del>
<del>Repeat password input</del>

*Change location of `Agree to our Terms & Stuff` to be under the Signup button, without checkbox input and change message to be `By clicking Signup, you agree with our Terms & Privacy`*

Join the Discord channel for this issue [Signup Channel](https://discord.gg/46mB95)

Compete with colleagues in #3  
Let's see result better than them!

**Don't forget to check [Atlas Track project](https://github.com/PresKhaled/atlas/projects/1) instructions (Information, Pinned columns) before contribution**

**UI**

![Signup UI](https://user-images.githubusercontent.com/58700627/79996018-3cf8ab00-84b8-11ea-9125-79817f4dc776.png)

**Comment by MarwanSallum** [comment]
adding utilities folder and contain constants  for imagsPath variable , kGradient , kBoxShadow , dividerColor , 

adding buildDivider method in include file 

adding signin page

![Screenshot_20200423-080648](https://user-images.githubusercontent.com/48675836/80061776-d49edd80-853a-11ea-8026-dc11f55dea76.jpg)
