### ISSUE TITLE
Aside menu (Drawer)

### ISSUE THREAD

**Issue by PresKhaled** [PresKhaled/atlas#5]
### You have to done this togther!

@ahmedragab287 
@AyadAlmamary 
@FarajElmadhi 

**Entry point:**
  - /inc/drawer.dart

Join Discord channel for this issue [Drawer Channel](https://discord.gg/PYtVAU)

![Aside menu (Drawer)](https://user-images.githubusercontent.com/58700627/79999727-8ba84400-84bc-11ea-8216-58ea70ef3e75.png)

**Comment by ragaba287** [comment]
Some parts are missing:
<del>1. The button gradient and shadow </del>
<del>2. The fonts need to be checked</del>
<del>3. The icons are not the same as the Design</del>
<del>4. The check mark on the photo</del>

![Screenshot_20200423-101734](https://user-images.githubusercontent.com/37620588/80084960-e2169080-8557-11ea-8be3-f92adef27b8f.png)

**Comment by PresKhaled** [comment]
> Some parts are missing:
> 
> 1. The button gradient and shadow
> 2. The fonts need to be checked
> 3. The icons are not the same as the Design
> 4. The check mark on the photo
> 
> ![Screenshot_20200423-101734](https://user-images.githubusercontent.com/37620588/80084960-e2169080-8557-11ea-8be3-f92adef27b8f.png)

**Good Job!** ✨ 

**Addtions to what you said:**
  <del>- Image need more borderRadius </del>
            - Use a propper margin and padding values
  <del>- Small the font with propper letter-spacing</del>
  <del>- Extract icons as png from PSD</del>

_After that make a pull request_

**Comment by ragaba287** [comment]
I think everything is done now 
But need to test on different resolution size 

![Screenshot_20200423-165354](https://user-images.githubusercontent.com/37620588/80114334-bb6e4f00-8583-11ea-8943-4e023727eea8.png)

@PresKhaled which margin

**Comment by PresKhaled** [comment]
> I think everything is done now
> But need to test on different resolution size
> 
> ![Screenshot_20200423-165354](https://user-images.githubusercontent.com/37620588/80114334-bb6e4f00-8583-11ea-8943-4e023727eea8.png)
> 
> @PresKhaled which margin

You did good ✨ 

Two more things 😄 
  - raise the checkmark a little
  - check the spaces in the image below

After that follow these steps: [Code Lifecycle in Atlas](https://github.com/PresKhaled/atlas/projects/1#card-36866921)

![Top Drawer part](https://user-images.githubusercontent.com/58700627/80141983-bcff3d80-85aa-11ea-8f36-0340656a109d.png)

**Comment by ahmedragab287** [comment]
> You did good ✨
> 
> Two more things 😄
> 
><del> * raise the checkmark a little</del>
> <del>* check the spaces in the image below</del>
> 
> <del>After that follow these steps: [Code Lifecycle in Atlas](https://github.com/PresKhaled/atlas/projects/1#card-36866921)</del>
> 
> ![Top Drawer part](https://user-images.githubusercontent.com/58700627/80141983-bcff3d80-85aa-11ea-8f36-0340656a109d.png)

✔**pushed to release-short   ##-live**

**Comment by ragaba287** [comment]
![Screenshot_1587751880](https://user-images.githubusercontent.com/37620588/80243848-3f016c00-8668-11ea-8806-3755a996d130.png)

**Comment by PresKhaled** [comment]
@ahmedragab287 
Excellent! 💯
