### ISSUE TITLE
Reviews UI

### ISSUE THREAD

**Issue by PresKhaled** [PresKhaled/atlas#8]
### Reviews UI need to be done!

  - Do the part that you like
  - Cooperate in the same part
  - Agree to assign a part to each of you in the Discord channel

Join the Discord channel for this issue [Reviews Channel](https://discord.gg/mgB5Ex)

**Don't forget to check [Atlas Track project](https://github.com/PresKhaled/atlas/projects/1) instructions (Information, Pinned columns) before contribution**

**UI:**

![Reviews UI](https://user-images.githubusercontent.com/58700627/80005851-71726400-84c4-11ea-9eca-bfa60acee87a.png)

**Comment by ragaba287** [comment]
Top is done
**Missing :**
**1. The list for the items**
**2. The review Item**

![Screenshot_1587917896](https://user-images.githubusercontent.com/37620588/80314336-430cc580-87f1-11ea-8fb5-a007977aebf1.png)

**Comment by ragaba287** [comment]
Reviews is done 

**Missing :**
- **Check the list** 


 
![Screenshot_1587995828](https://user-images.githubusercontent.com/37620588/80384683-79a41800-88a5-11ea-9b98-87fd818415db.png)

**Comment by PresKhaled** [comment]
**All good, fantastic work!** ✨ 

_a little note:_ Colors, spaces, sizes needs to be more accurate
